[versions]
detekt = "1.18.1"
koTest = "4.6.3"
ktlint = "0.43.0"
coroutines = "1.5.1"
timber = "5.0.1"
unicorn = "0.9.1"
rxRelay = "2.1.1"
compose = "1.0.5"
accompanist = "0.18.0"

[libraries]
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }
kotest-junit-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "koTest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "koTest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "koTest" }
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
unicornRxJava2 = { module = "ru.dimsuz:unicorn-rxjava2", version.ref = "unicorn" }
rxRelay = { module = "com.jakewharton.rxrelay2:rxrelay", version.ref = "rxRelay" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
composeMaterialIcons = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
composeTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
composeRuntime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
composeRuntimeRxJava = { module = "androidx.compose.runtime:runtime-rxjava2", version.ref = "compose" }
accompanistInsets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }

[bundles]
koTest = [ "kotest-junit-runner", "kotest-assertions-core", "kotest-property" ]
coroutines = [ "coroutines-core" ]
compose = [ "composeUi", "composeMaterial", "composeMaterialIcons", "composeTooling", "composeRuntime", "composeRuntimeRxJava", "accompanistInsets"]
